<a href="https://colab.research.google.com/github/vikashkumar97983282-glitch/machine-learning/blob/main/DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data={
    "name":['vikash','aashif','satyam','ankit','ankur'],
    "marks":[45,78,58,48,52],
    "city":['delhi','mumbai','kolkata','chennai','surat']

}

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df

     name  marks     city
0  vikash     45    delhi
1  aashif     78   mumbai
2  satyam     58  kolkata
3   ankit     48  chennai
4   ankur     52    surat

In [ ]:
df.to_csv("data.csv",index=False)

In [ ]:
df.to_excel("data.xlsx",index=False)

In [ ]:
df.to_json("data.json",index=False)

#columns,rows  &  what types of data  &  missing data

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   marks   5 non-null      int64
 2   city    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes
None

In [ ]:
df.head(2)

     name  marks    city
0  vikash     45   delhi
1  aashif     78  mumbai

In [ ]:
df.tail(2)

    name  marks     city
3  ankit     48  chennai
4  ankur     52    surat

In [ ]:
df.describe()

         marks
count   5.0000
mean   56.2000
std    13.1225
min    45.0000
25%    48.0000
50%    52.0000
75%    58.0000
max    78.0000

In [ ]:
df=pd.DataFrame(data)

In [ ]:
print(df)

     name  marks     city
0  vikash     45    delhi
1  aashif     78   mumbai
2  satyam     58  kolkata
3   ankit     48  chennai
4   ankur     52    surat

In [ ]:
print(df)
print(f'columns= {df.shape}')
print(f'columns name= {df.columns}')

     name  marks     city
0  vikash     45    delhi
1  aashif     78   mumbai
2  satyam     58  kolkata
3   ankit     48  chennai
4   ankur     52    surat
columns= (5, 3)
columns name= Index(['name', 'marks', 'city'], dtype='object')

#selecting columns

In [ ]:
print(df['name'])

0    vikash
1    aashif
2    satyam
3     ankit
4     ankur
Name: name, dtype: object

#filtering rows

In [ ]:
subset=df[['name','city']]

In [ ]:
print(subset)

     name     city
0  vikash    delhi
1  aashif   mumbai
2  satyam  kolkata
3   ankit  chennai
4   ankur    surat

In [ ]:
print(df[["name","city"]])

     name     city
0  vikash    delhi
1  aashif   mumbai
2  satyam  kolkata
3   ankit  chennai
4   ankur    surat

#highest salary boolean type output

In [ ]:
print(df['marks'] > 48)

0    False
1     True
2     True
3    False
4     True
Name: marks, dtype: bool

#highest value in DataFrame

In [ ]:
highest=df[df['marks']>48]

In [ ]:
print(highest)

     name  marks     city
1  aashif     78   mumbai
2  satyam     58  kolkata
4   ankur     52    surat

In [ ]:
filtered=df[(df['marks']>48) & (df['city']=='surat')]

In [ ]:
print(filtered)

    name  marks   city
4  ankur     52  surat

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

#**adding** **data in dataframe**

In [ ]:
print(df)

     name  marks     city
0  vikash     45    delhi
1  aashif     78   mumbai
2  satyam     58  kolkata
3   ankit     48  chennai
4   ankur     52    surat

In [ ]:
df["grade"]=['C','B+','C+','C','C+']

In [ ]:
df["age"]=[21,22,24,20,16]

In [ ]:
print(df)

     name  marks     city grade  age
0  vikash     45    delhi     C   21
1  aashif     78   mumbai    B+   22
2  satyam     58  kolkata    C+   24
3   ankit     48  chennai     C   20
4   ankur     52    surat    C+   16

#adding data from specific index

In [ ]:
df.insert(0,'student_id',[101,102,103,104,105])

In [ ]:
print(df)

   student_id    name  marks     city grade  age
0         101  vikash     45    delhi     C   21
1         102  aashif     78   mumbai    B+   22
2         103  satyam     58  kolkata    C+   24
3         104   ankit     48  chennai     C   20
4         105   ankur     52    surat    C+   16

#updating value in dataframe

In [ ]:
df.loc[0,'marks']=62

In [ ]:
print(df)

   student_id    name  marks     city grade  age
0         101  vikash     62    delhi     C   21
1         102  aashif     78   mumbai    B+   22
2         103  satyam     58  kolkata    C+   24
3         104   ankit     48  chennai     C   20
4         105   ankur     52    surat    C+   16

In [ ]:
df['marks']=df['marks']+7

In [ ]:
print(df)

   student_id    name  marks     city grade  age
0         101  vikash     69    delhi     C   21
1         102  aashif     85   mumbai    B+   22
2         103  satyam     65  kolkata    C+   24
3         104   ankit     55  chennai     C   20
4         105   ankur     59    surat    C+   16

#removing data in dataframe

In [ ]:
df.drop(columns=['grade'] ,inplace=True)

In [ ]:
print(df)

   student_id    name  marks     city  age
0         101  vikash     69    delhi   21
1         102  aashif     85   mumbai   22
2         103  satyam     65  kolkata   24
3         104   ankit     55  chennai   20
4         105   ankur     59    surat   16

In [ ]:
df.drop(columns=['age','student_id'],inplace=True)

In [ ]:
print(df)

     name  marks     city
0  vikash     69    delhi
1  aashif     85   mumbai
2  satyam     65  kolkata
3   ankit     55  chennai
4   ankur     59    surat

#handling missing data

In [ ]:
data_1={
    "name":['vikash','himanshu','satyam','ankit','ankur'],
    "marks":[45,None,58,48,52],
    "city":['delhi',None,'kolkata','chennai','surat']

}

In [ ]:
df_1=pd.DataFrame(data_1)

In [ ]:
print(df_1)

       name  marks     city
0    vikash   45.0    delhi
1  himanshu    NaN     None
2    satyam   58.0  kolkata
3     ankit   48.0  chennai
4     ankur   52.0    surat

In [ ]:
print(df_1.isnull())

    name  marks   city
0  False  False  False
1  False   True   True
2  False  False  False
3  False  False  False
4  False  False  False

In [ ]:
print(df_1.isnull().sum(0))

name     0
marks    1
city     1
dtype: int64

In [ ]:
#df_1.dropna(inplace=True)

In [ ]:
print(df_1)

       name  marks     city
0    vikash   45.0    delhi
1  himanshu    NaN     None
2    satyam   58.0  kolkata
3     ankit   48.0  chennai
4     ankur   52.0    surat

In [ ]:
df["marks"]=df["marks"].interpolate(method="linear")

In [ ]:
print(df_1)

       name  marks     city
0    vikash   45.0    delhi
1  himanshu    NaN     None
2    satyam   58.0  kolkata
3     ankit   48.0  chennai
4     ankur   52.0    surat

#sorting & aggregation

#sorting

In [ ]:
data2={
    "name":['vikash','himanshu','satyam','ankit','ankur'],
    "age":[45,67,58,48,52],
    "salary":[20000,45000,68000,42000,35000]

}

In [ ]:
df1=pd.DataFrame(data2)

In [ ]:
print(df1)

       name  age  salary
0    vikash   45   20000
1  himanshu   67   45000
2    satyam   58   68000
3     ankit   48   42000
4     ankur   52   35000

In [ ]:
df1.sort_values(by="age", ascending=True , inplace=True)

In [ ]:
print(df1)

       name  age  salary
0    vikash   45   20000
3     ankit   48   42000
4     ankur   52   35000
2    satyam   58   68000
1  himanshu   67   45000

In [ ]:
df1.sort_values(by="age", ascending=False, inplace=True)

In [ ]:
print(df1)

       name  age  salary
1  himanshu   67   45000
2    satyam   58   68000
4     ankur   52   35000
3     ankit   48   42000
0    vikash   45   20000

In [ ]:
df1.sort_values(by=["age","salary"], ascending=[True,False], inplace=True)

In [ ]:
print(df1)

       name  age  salary
0    vikash   45   20000
3     ankit   48   42000
4     ankur   52   35000
2    satyam   58   68000
1  himanshu   67   45000

#aggregation

In [ ]:
data3={
    "name":['vikash','himanshu','satyam','ankit','ankur'],
    "age":[25,67,35,25,35],
    "salary":[20000,45000,68000,42000,35000]

}

In [ ]:
df2=pd.DataFrame(data3)

In [ ]:
print(df2)

       name  age  salary
0    vikash   25   20000
1  himanshu   67   45000
2    satyam   35   68000
3     ankit   25   42000
4     ankur   35   35000

In [ ]:
avg_sal=df2["salary"].mean()

In [ ]:
print(avg_sal)

42000.0

In [ ]:
grouped=df2.groupby("age")["salary"].sum()

In [ ]:
print(grouped)

age
25     62000
35    103000
67     45000
Name: salary, dtype: int64

In [ ]:
multi_grouped=df2.groupby(["age","name"])["salary"].sum()

In [ ]:
print(multi_grouped)

age  name
25   ankit       42000
     vikash      20000
35   ankur       35000
     satyam      68000
67   himanshu    45000
Name: salary, dtype: int64

#merging & joining dataset

In [ ]:
import pandas as pd

In [ ]:
df_customers=pd.DataFrame({
    "cust_id":[101,102,103,104],
    "name":['vikash','himanshu','satyam','ankit']
}
)

In [ ]:
df_orders=pd.DataFrame({
    "cust_id":[101,102,105,106],
    "order_amt":[5000,2000,3200,4100]
})

In [ ]:
df_merged=pd.merge(df_customers, df_orders, on='cust_id', how='inner')

In [ ]:
print(df_merged)

   cust_id      name  order_amt
0      101    vikash       5000
1      102  himanshu       2000

In [ ]:
df_merged=pd.merge(df_customers, df_orders, on='cust_id', how='outer')

In [ ]:
print(df_merged)

   cust_id      name  order_amt
0      101    vikash     5000.0
1      102  himanshu     2000.0
2      103    satyam        NaN
3      104     ankit        NaN
4      105       NaN     3200.0
5      106       NaN     4100.0

In [ ]:
df_merged=pd.merge(df_customers, df_orders, on='cust_id', how='left')

In [ ]:
print(df_merged)

   cust_id      name  order_amt
0      101    vikash     5000.0
1      102  himanshu     2000.0
2      103    satyam        NaN
3      104     ankit        NaN

In [ ]:
df_merged=pd.merge(df_customers, df_orders, on='cust_id', how='right')

In [ ]:
print(df_merged)

   cust_id      name  order_amt
0      101    vikash       5000
1      102  himanshu       2000
2      105       NaN       3200
3      106       NaN       4100

In [ ]:
df_customers=pd.DataFrame({
    "cust_id":[101,102,103,104],
    "name":['vikash','himanshu','satyam','ankit']
}
)

In [ ]:
df_orders=pd.DataFrame({
    "cust_id":[105,106,107,108],
    "order_amt":[5000,2000,3200,4100]
})

In [ ]:
df_concat=pd.concat([df_customers,df_orders], ignore_index=True)

In [ ]:
print(df_concat)

   cust_id      name  order_amt
0      101    vikash        NaN
1      102  himanshu        NaN
2      103    satyam        NaN
3      104     ankit        NaN
4      105       NaN     5000.0
5      106       NaN     2000.0
6      107       NaN     3200.0
7      108       NaN     4100.0

In [ ]:
df_concat=pd.concat([df_customers,df_orders], axis=1, ignore_index=True)

In [ ]:
print(df_concat)

     0         1    2     3
0  101    vikash  105  5000
1  102  himanshu  106  2000
2  103    satyam  107  3200
3  104     ankit  108  4100

In [ ]:
val={1,2,1,2}
val2={1,2}

print(1 in val)
#print(val2.issuperset(val))
print(val)

True
{1, 2}

In [ ]:
def fun(n):
    count = 0
    i = n
    while i > 0:
        for j in range(i):
            count += 1
        i //= 2
    return count
print(fun(5))

8

In [ ]:
class Node:
  def __init__(self, item=None, next=None):
    self.item = item
    self.next = next
class SLL:
  def __init__(self, start=None):
    self.start = start

  def is_empty(self):
    return self.start == None

  def insert_at_start(self, data):
    n = Node(data, self.start)
    self.start = n

  def insert_at_last(self,data):
    n = Node(data)
    if not self.is_empty():
      temp = self.start
      while temp.next is not None:
        temp = temp.next
      temp.next = n
    else:
      self.start = n

  def search(self, data):
    temp = self.start
    while temp is not None:
      if temp.item == data:
        return temp
      temp = temp.next
    return None

  def insert_after(self, temp, data):
    if temp is not None:
      n = Node(data, temp.next)
      temp.next = n

  def print_list(self):
    temp = self.start
    while temp is not None:
      print(temp.item, end=" ")
      temp = temp .next

  def delete_first(self):
    if not self.start is None:
      self.start = self.start.next

  def delete_last(self):
    if self.start is None:
      pass
    elif self.start.next is None:
      self.start = None
    else:
      temp = self.start
      while temp.next.next is not None:
        temp = temp.next
      temp.next = None

  def delete_item(self,data):
    if self.start is None:
      pass
    elif self.start.next is None:
      if self.start.item == data:
        self.start = None
    else:
      temp = self.start
      if temp.item == data:
        self.start = temp.next
      else:
        while temp.next is not None:
          if temp.next.item == data:
            temp.next = temp.next.next
            break
          temp = temp.next

  def __iter__(self):
    return SLLIterator(self.start)


class SLLIterator:
  def __init__(self,start):
    self.current = start

  def __iter__(self):
    return self

  def __next__(self):
    if not self.current:
      raise StopIteration
    data =self.current.item
    self.current = self.current.next
    return data

mylist = SLL()
mylist.insert_at_start(20)
mylist.insert_at_start(10)
mylist.insert_at_last(30)
mylist.insert_after(mylist.search(20), 25)
mylist.print_list()

mylist.delete_item(25)
print()

for x in mylist:
  print(x, end=" ")
print()

mylist.is_empty()

# mylist.print_list()

10 20 25 30
10 20 30

False

In [ ]:
mylist.is_empty()

False

In [ ]:
class Node:
  def __init__(self, item=None, next=Node):
    self.item = item
    self.next = next

class SLL:
  def __init__(self, head=None):
    self.head = head

  def insert_at_start(self, data):
    n = Node(data, self.head)
    self.head = n





list1 = Node()
list1.insert_at_start(10)

AttributeError: 'Node' object has no attribute 'insert_at_start'

In [ ]:
a = [None, None, None, None]
a[1:2] = [2]
print(a)

[None, 2, None, None]

In [ ]:
keys = ['vikash',4,'ce','btech']
value = ['name','roll_no','branch','year']

data = dict(zip(keys,value))
print(data)

{'vikash': 'name', 4: 'roll_no', 'ce': 'branch', 'btech': 'year'}

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('Titanic-Dataset.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Titanic-Dataset.csv'

In [ ]:
data.head(3)

In [ ]:
data.count()

In [ ]:
(data['Age'].isnull().sum()/data.isnull().sum())*100

In [ ]:
class car:
	def __init__(self):
		self.brand = ["Toyota","Mahindra"]
		self.name = ["Fortuner","Hyryder","Thar","Scorpio"]
		self.speed = [180,160,120,160]
		self.fuel = [5,2,2,4]


	def buy(self):
		print("1. Toyota\n2. Mahindra\n")
		self.buy = int(input("Select brand of car:-"))
		if (self.buy == 1):
			print(f"1. {self.name[0]} \n2. {self.name[1]}\n")
			self.car_name = int(input("Select car name:-"))
			if  (self.car_name == 1):
				print("\nCongratulation! your new car")
				print("Car name:- ",self.name[0])
				print(f"Car speed:- {self.speed[0]} km/h")
				print(f"Car fuel:- {self.fuel[0]} ltr")
			elif (self.car_name == 2):
				print("\nCongratulation! your new car")
				print("Car name:- ",self.name[1])
				print(f"Car speed:- {self.speed[1]} km/h")
				print(f"Car fuel:- {self.fuel[1]} ltr")
			else:
				print("\nInvalid! Select car")

		elif (self.buy == 2):
			print("1. Fortuner\n2. Hyryder\n")
			self.car_name = int(input("Select car name:-"))
			if  (self.car_name == 1):
				print("\nCongratulation! your new car")
				print("Car name:- ",self.name[0])
				print(f"Car speed:- {self.speed[0]} km/h")
				print(f"Car fuel:- {self.fuel[0]} ltr")
			elif (self.car_name == 2):
				print("\nCongratulation! your new car")
				print("Car name:- ",self.name[1])
				print(f"Car speed:- {self.speed[1]} km/h")
				print(f"Car fuel:- {self.fuel[1]} ltr")
			else:
				print("Invalid! Select car")



Car = car()
Car.buy()

In [ ]:
class parent:
  def __init__(self):
    self.father = input("enter father's name:-")
    self.mother = input("enter mother's name:-")

class child(parent):
  def __init__(self,parent):
    self.parent = parent
    self.a = int(input("\nhow many your child:-"))

  def display(self):
    i = 1
    while(i <= self.a):
        self.name = input(f"\nenter child {i} name:-")
        self.age = input(f"enter child {i} age:-")
        print(f"\n          your child {i}")
        print(f"name:- {self.name}")
        print(f"age:- {self.age}")
        print(f"father's name:- {self.parent.father}")
        print(f"mother's name:- {self.parent.mother}")
        print("\n")
        i+=1

p = parent()
dt = child(p)
dt.display()

In [ ]:
class Student:
  def __init__(self,name,branch):
    self.name = name
    self.branch = branch

  @staticmethod
  def message():
    print("welcome to rku")
    print()


  def display(self):
    print(f"your name {self.name}")
    print(f"your branch {self.branch}")

s1 = Student("vikash","Computer Engineering")
s1.message()
s1.display()

In [ ]:
class Bank:
  def __init__(self, acc, name, bal):
    self.account = acc
    self.name = name
    self.balance = bal

  def debit(self,amount):
    self.balance -= amount
    print(f"{amount} debit from your account")

  def credit(self,amount):
    self.balance += amount
    print(f"{amount} credit to your account")


b = Bank(12345,"vikash kumar",50000)
b.debit(1000)
b.credit(2000)
print(b.balance)

In [ ]:
class Bank:
  print("                  Welcome to Kotak Mahindra Bank")
  def __init__(self):
    self.account = [1122,3344,1234,4321]
    self.name = ["vikash kumar", "ashif ali","raj vardhan", "rahul kumar"]
    self.balance = [50000,60000,70000,80000]


  def user(self):
    self.name1 = input("enter your name:-")
    self.account1 = int(input("enter your account number:-"))


  def process(self):
    self.newbalance = 0
    for i in range(len(self.name)):
      if (self.name1 == self.name[i] and self.account1 == self.account[i]):
        self.newbalance = self.balance[i]
        #print(f"\nyour name {self.name[i]}")
        #print(f"your account number {self.account[i]}")
        #print(f"your balance {self.balance[i]}")
        print("\nLogin sucessfully!")
        break
      else:
        print("invalid user!")
        break


  def operation(self):
    print("\n1.Debit \n2.Credit \n3.Check balance \n4.Account detail")
    self.choice = int(input("\nchoose given options (1/2/3/4)"))
    print()

    if (self.choice == 1):
      self.amount = int(input("enter your amount:-"))
      self.newbalance -= self.amount
      return (f"{self.amount}rs debit from your account")
    elif (self.choice == 2):
      self.amount = int(input("enter your amount:-"))
      self.newbalance += self.amount
      return (f"{self.amount}rs credit to your account")
    if (self.choice == 3):
      self.pin = int(input("enter your account number:-"))
      if (self.pin == self.account1):
        return (f"your account balance:- {self.newbalance}")
    if (self.choice == 4):
      self.pin = int(input("enter your account:-"))
      if (self.pin == self.account1):
        print()
        print("      your Account Details")
        print(f"your name:-{self.name1}")
        print(f"your account number:-{self.account1}")
    else:
      print("invalid options")




b = Bank()
b.user()
b.process()
b.operation()

In [ ]:
class Bank:
  print("                  Welcome to Kotak Mahindra Bank")
  def __init__(self):
    self.account = [1122,3344,1234,4321]
    self.name = ["vikash kumar", "ashif ali","raj vardhan", "rahul kumar"]
    self.balance = [50000,60000,70000,80000]


  def user(self):
    self.name1 = input("enter your name:-")
    self.account1 = int(input("enter your account number:-"))


  def process(self):
    self.newbalance = 0
    for i in range(len(self.name)):
      if (self.name1 == self.name[i] and self.account1 == self.account[i]):
        self.newbalance = self.balance[i]
        print("\nLogin sucessfully!")
        break
      else:
        print("invalid user!")
        break


  def operation(self):
    while True:
      print("\n1.Debit \n2.Credit \n3.Check balance \n4.Account detail")
      self.choice = int(input("\nchoose given options (1/2/3/4):-"))
      print()

      if (self.choice == 1):
        self.amount = int(input("enter your amount:-"))
        self.newbalance -= self.amount
        print(f"{self.amount}rs debit from your account")

      elif (self.choice == 2):
        self.amount = int(input("enter your amount:-"))
        self.newbalance += self.amount
        print(f"{self.amount}rs credit to your account")

      elif (self.choice == 3):
        self.pin = int(input("enter your account no:-"))
        if (self.pin == self.account1):
          print(f"your account balance:- {self.newbalance}")

      elif (self.choice == 4):
        self.pin = int(input("enter your account no:-"))
        if (self.pin == self.account1):
          print()
          print("      your Account Details")
          print(f"your name:-{self.name1}")
          print(f"your account number:-{self.account1}")

      else:
        print("invalid options")
      print()
      self.a = input("if you want continue(y/n):-")
      if (self.a == "n"):
        break





b = Bank()
b.user()
b.process()
b.operation()

In [ ]:
# Banking system operations with oops concepts
from time import sleep

class Bank:
  print("                  Welcome to Kotak Mahindra Bank")
  def __init__(self):
    self.account = [1122,3344,1234,4321]
    self.name = ["vikash kumar", "ashif ali","raj vardhan", "rahul kumar"]
    self.balance = [50000,60000,70000,80000]


  def user(self):
    self.name1 = input("enter your name:-")
    self.account1 = int(input("enter your account number:-"))

  def check(self):
    print("please wait ",end='')
    for i in range(10):
      print("@",end='')
      sleep(0.5)


  def process(self):
    self.newbalance = 0
    for i in range(len(self.name)):
      if (self.name1 == self.name[i] and self.account1 == self.account[i]):
        self.newbalance = self.balance[i]
        self.check()
        print("\nLogin sucessfully!")
        print(time.ctime())
        # operation function
        self.operation()
        break
      else:
        print("invalid user!")
        break


  def operation(self):
    while True:
      print(f"\n1.Debit {sleep(0.5)}\n2.Credit {sleep(0.5)}\n3.Check balance {sleep(0.5)}\n4.Account detail{sleep(0.5)}")
      self.choice = int(input("\nchoose given options (1/2/3/4):-"))
      print()

      if (self.choice == 1):
        self.amount = int(input("enter your amount:-"))
        self.newbalance -= self.amount
        print(f"{self.amount}rs debit from your account")

      elif (self.choice == 2):
        self.amount = int(input("enter your amount:-"))
        self.newbalance += self.amount
        print(f"{self.amount}rs credit to your account")

      elif (self.choice == 3):
        self.pin = int(input("enter your account no:-"))
        if (self.pin == self.account1):
          print(f"your account balance:- {self.newbalance}")

      elif (self.choice == 4):
        self.pin = int(input("enter your account no:-"))
        if (self.pin == self.account1):
          print()
          print("      your Account Details")
          print(f"your name:-{self.name1}")
          print(f"your account number:-{self.account1}")

      else:
        print("invalid options")
      print()
      self.a = input("if you want continue(y/n):-")
      if (self.a == "n"):
        break





b = Bank()
b.user()
b.process()
#b.operation()

In [ ]:
class cal:
  def __init__(self):
    print("Welcome to Calculator\n")

# functions of calculator
  def add(self):
    print(self.a + self.b)

  def sub(self):
    print(self.a - self.b)

  def mul(self):
    print(self.a * self.b)

  def div(self):
    print(self.a / self.b)

# get two nunmber from user
  def input(self):
    self.a = int(input("enter first number:-"))
    self.b = int(input("enter second number:-"))

 # choose equation from user
  def equation(self):
    print("\n1.addition\n2.subtraction\n3.multiplication\n4.division\n")
    self.user = int(input("choose equations:-"))

# opertaions method
  def operation(self):
    if (self.user == 1):
      self.add()
    elif (self.user == 2):
      self.sub()
    elif (self.user == 3):
      self.mul()
    elif (self.user == 4):
      self.div()
    else:
      print("thank you for the operation")

# drive the code of calculator
  def driver(self):
    while True:
      self.input()
      self.equation()
      self.operation()
      print()
      self.op = input("if you want continue(y/n):-")
      if (self.op == "n"):
        break


c = cal()
c.driver()

In [ ]:
class parent:
  def __init__(self):
    self.fname = "ramesh"

  def display(self):
    print(f"your father's name:-{self.fname}")

class child(parent):
  def __init__(self,cname):
    parent.__init__(self)
    self.cname = cname

  def display1(self):
    print(f"your name:-{self.cname}")
    super().display()


c1 = child("rakesh")
c1.display1()

In [ ]:
# class method
class person:
  name = "vikash kumar"
  def changename(self,name):
    person.name = name

p = person()
p.changename("rahul kumar")
print(p.name)
print(person.name)

In [ ]:
# class method2
class person:
  name = "vikash kumar"

  def changename(self,name):
    self.__class__.name = "rahul kumar"

p = person()
p.changename("rahul kumar")
print(p.name)
print(person.name)

In [ ]:
class person:
  name = "rahul kumar"

  @classmethod
  def changename(cls,name):
    cls.name = name

p = person()
p.changename("vikash kumar")
print(p.name)
print(person.name)

In [ ]:
#property decorator
class student:
  def __init__(self,phy,chem,math):
    self.phy = phy
    self.chem = chem
    self.math = math

  @property
  def percentage(self):
    return str((self.phy + self.chem + self.math)/3)+"%"

st = student(90,85,86)
st.percentage
st.phy = 95
st.percentage

In [ ]:
class student:
  def __init__(self,name,marks):
    self.name = name
    self.marks = marks
  def avg(self):
    self.avg_mark = 0
    for i in range(len(self.marks)):
      self.avg_mark += self.marks[i]



  def show(self):
    self.avg()
    print(f"your name:-{self.name}")
    print(f"your percentage:-{self.avg_mark/len(self.marks)}%")

s = student("vikash kumar",[90,86,84])
#s.avg()
s.show()

In [ ]:
a = [10,15,42,15]
b=0
for i in range(len(a)):
  b += a[i]
print(b)

In [ ]:
s1 = {1,2,6,4}
s2 = {8,3,7,5}
s3 = s1.union(s2)
print(s2)

In [ ]:
class student:
  a = input("enter name:-")
  def user(self):
    self.show()
    print(f"enter your name:-{self.a}")

  @staticmethod
  def show():
    print("vikash kumar")

s = student()
s.user()

In [ ]:
a = input("enter name:-")
for i in range(len(a)):
  if (a[i] == " "):
    f = a.split()

print("first name:-",f[0])
print("second name:-",f[1])
print("last name:-",f[2])

In [ ]:
def is_leap(year):
    leap = False

    if ((year%4==0 and year%100!=0) | year%400==0):
      leap = True

    return leap

year = int(input())
is_leap(year)

In [ ]:
import string
print(string.ascii_lowercase)

In [ ]:
def print_rangoli(size):
  for i in range(size):
    s = []
    s.extend([chr(c) for c in range(96+size, 96+size-i-1, -1)])
    s.extend([chr(c) for c in range(96+size, 96+size-i, -1)][::-1])
    print("-".join(s).center(4*size-3,'-'))


  for i in range(size-2, -1, -1):
    s = []
    s.extend([chr(c) for c in range(96+size, 96+size-i-1, -1)])
    s.extend([chr(c) for c in range(96+size, 96+size-i, -1)][::-1])
    print("-".join(s).center(4*size-3,'-'))


print_rangoli(10)

In [ ]:
from datetime import date
class person:
  def __init__(self,name,country,dob):
    self.name = name
    self.country = country
    self.dob = dob
  def age(self):
    today = date.today()
    age = today.year - self.dob.year
    if today < date(today.year, self.dob.month, self.dob.day):
      age -= 1
    return age
  def show(self):
    print(f"your name:-{self.name}")
    print(f"your country:-{self.country}")
    print(f"your age:-{self.age()}")

c = person("rakesh","india", date(2008,11,16))
c.show()

In [ ]:
class node:
  def __init__(self,item,next=None):
    self.item = item
    self.next = next

class sll:
  def __init__(self,start=None):
    self.start = start

  def is_empty(self):
    return self.start==None

  def insert_at_start(self,data):
    n = node(data,self.start)
    self.start = n


  def traverse(self):
    curr = self.start
    while curr is not None:
      print(curr.item,end=" ")
      curr = curr.next

  def insert_at_last(self,data):
    n = node(data)

    if self.start is None:
      self.start = n
      return
    curr = self.start
    while curr.next == None:
      curr = curr.next
    curr.next = n


s = sll()
s.is_empty()
s.insert_at_start(22)
s.insert_at_start(33)
s.insert_at_start(44)
s.traverse()
s.insert_at_last(15)
s.traverse()

In [ ]:
def bubble_sort(list1):
  flags=False
  for r in range(1,len(list1)):
    flags=False
    for i in range(len(list1)-r):
      if (list1[i]>list1[i+1]):
        list1[i],list1[i+1] = list1[i+1],list1[i]
        flags=True
    if (flags==False):
      break


l=[10,15,4,23,0]
bubble_sort(l)
print(l)

In [ ]:
from time import sleep
def fun():
  for i in range(50):
    print("i love you")
    sleep(0.5)

fun()

In [ ]:
import time

print("Stopwatch started...")
start = time.time()

time.sleep(5)   # wait for 5 seconds

end = time.time()
print("Elapsed time:", end - start, "seconds")

In [ ]:
start = time.perf_counter()

# Some code
for i in range(1000000):
    pass

end = time.perf_counter()
print("Execution time:", end - start, "seconds")

In [ ]:
from time import sleep
print(time.ctime())

In [ ]:
def choice(self):
  ch = ["1.Debit", "2.Credit", "3.Check balance", "4.Account detail"]
  for i in range(len(ch)):
      for j in range(len(ch[i])):
          print(ch[j],end='')
      print()

In [ ]:
pip install emoji

In [ ]:
pip install pyjokes

In [ ]:
pip install cowpy

In [ ]:
from cowpy import cow
msg = cow.Cowacter().milk("Python is awesome!")
print(msg)

In [ ]:
import emoji
print(emoji.emojize("Python is :fire: :red_heart:"))

In [ ]:
import pyjokes
print(pyjokes.get_joke())

In [ ]:
import time

for i in range(10):
    print("LED ON")
    time.sleep(1)   # 1 second delay
    print("LED OFF")
    time.sleep(1)

In [ ]:
from time import sleep
import emoji

for i in range(5):
  print(emoji.emojize("hello :red_heart: :eggplant:"))
  sleep(0.5)

In [ ]:
import getpass

# Hide password while typing
password = int(getpass.getpass("Enter Password: "))

print("You entered:", password)  # (Just to show it's stored)
print(type(password))

In [ ]:
# Banking system operations with oops concepts
from time import sleep
import getpass
import time

class Bank:
  print("                  ",end='')
  a = "Welcome to Kotak Mahindra Bank"
  for i in range(len(a)):
      print(a[i],end='')
      sleep(0.1)
  print("\n")


  def __init__(self):
    self.account = [1122,3344,1234,4321]
    self.name = ["vikash kumar", "ashif ali","raj vardhan", "rahul kumar"]
    self.balance = [50000,60000,70000,80000]


  def user(self):
    self.name1 = input("enter your name:-")
    self.account1 = int(getpass.getpass("enter your account number:-"))

  def check(self):
    print("please wait ",end='')
    for i in range(10):
      print("@",end='')
      sleep(0.5)

  def choices(self):
      ch = ["1.Debit", "2.Credit", "3.Check balance", "4.Account detail", "5.Exit"]
      for i in range(len(ch)):
          for j in range(len(ch[i])):
              print(ch[i][j],end='')
              sleep(0.03)
          print("")


  def process(self):
    self.newbalance = 0
    for i in range(len(self.name)):
      if (self.name1 == self.name[i] and self.account1 == self.account[i]):
        self.newbalance = self.balance[i]
        self.check()
        print("\nLogin sucessfully!")
        print(time.ctime())
        # operation function
        self.operation()
        break
      else:
        print("invalid user!")
        break


  def operation(self):
    while True:
      print()
      self.choices()
      self.choice = int(input("\nchoose given options (1/2/3/4):-"))
      print()

      if (self.choice == 1):
        self.amount = int(input("enter your amount:-"))
        self.newbalance -= self.amount
        print(f"{self.amount}rs debit from your account")

      elif (self.choice == 2):
        self.amount = int(input("enter your amount:-"))
        self.newbalance += self.amount
        print(f"{self.amount}rs credit to your account")

      elif (self.choice == 3):
        self.pin = int(getpass.getpass("enter your account no:-"))
        if (self.pin == self.account1):
          print(f"your account balance:- {self.newbalance}")

      elif (self.choice == 4):
        self.pin = int(getpass.getpass("enter your account no:-"))
        if (self.pin == self.account1):
          print()
          print("      your Account Details")
          print(f"your name:-{self.name1}")
          print(f"your account number:-{self.account1}")

      else:
        print("thanks for visit")
      print()
      self.a = input("if you want continue(y/n):-")
      if (self.a == "n"):
        break





b = Bank()
b.user()
b.process()
#b.operation()

In [ ]:
pip install pyfiglet

In [ ]:
import pyfiglet
banner = pyfiglet.figlet_format("Vikash kumar")
print(banner)

In [ ]:
from kivy.app import App
from kivy.uix.button import Button

class MyApp(App):
    def build(self):
        return Button(text="Hello Kivy!")

MyApp().run()

In [ ]:
class student:
  def __init__(self):
    self.user()

  def user(self):
    self.name=input("enter your name:-")
    self.age=int(input("enter your age:-"))
    self.roll=int(input("enter your roll:-"))
    self.show()


  def show(self):
    print(f"your name:-{self.name}")
    print(f"your age:-{self.age}")
    print(f"your roll no:-{self.roll}")
    self.user()

s1=student()
#s1.show()

In [ ]:
class student:
  def __init__(self):
    self.user()

  def user(self):
    self.name = input("enter your name:-")
    self.marks = int(input("enter your marks:-"))
    self.show()

  def show(self):
    print(f"\nyour name:-{self.name}")
    print(f"your marks:-{self.marks}")
    self.user()


s1=student()

enter your name:-12
enter your marks:-13

your name:-12
your marks:-13
enter your name:-knjv
enter your marks:-20

your name:-knjv
your marks:-20
enter your name:-dhd
enter your marks:-45

your name:-dhd
your marks:-45

KeyboardInterrupt: Interrupted by user

In [ ]:
pip install tensorflow pillow numpy

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (11.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.18.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.5)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
import tensorflow as tf
import numpy as np
from PIL import Image

# Load pre-trained model
model = tf.keras.applications.MobileNetV2(weights="imagenet")

# Load image
img = Image.open("images.webp").resize((224, 224))

# Convert image to array
img_array = np.array(img)

# Expand dimension (important)
img_array = np.expand_dims(img_array, axis=0)

# Preprocess image
img_array = tf.keras.applications.mobilenet_v2.preprocess_input(img_array)

# Predict
predictions = model.predict(img_array)

# Decode result
result = tf.keras.applications.mobilenet_v2.decode_predictions(predictions, top=1)

# Print result
print("Detected Object:", result[0][0][1])
print("Confidence:", result[0][0][2])

1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step
Detected Object: Yorkshire_terrier
Confidence: 0.9328542